apiVersion: v1
kind: Secret
metadata:
  name: openai-gpt-api-secret
type: Opaque
data:
  OPENAI_GPT_API_KEY: "c2stcHJvai1MdWdXS00wS08tZTBUMWNEMHhDYmNZUTRKcUl2WHh0MmZPM09wUEo3R3c5azdSOTRMVTFRV3hRUnJldGhuaVlSUnRtbXBCMnZaX1QzQmxia0ZKbS1VcWtCV1NpalczV1B4NmgxN2ZMMC1FOU5hVE04cW5RZm1MenhXV013WTM4ejV3S29GYzF0LVQ3MWZoODhKTUUwU1JKTkFmb0E="
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-dalle-api-secret
type: Opaque
data:
  OPENAI_DALLE_API_KEY: "c2stcHJvai1MdWdXS00wS08tZTBUMWNEMHhDYmNZUTRKcUl2WHh0MmZPM09wUEo3R3c5azdSOTRMVTFRV3hRUnJldGhuaVlSUnRtbXBCMnZaX1QzQmxia0ZKbS1VcWtCV1NpalczV1B4NmgxN2ZMMC1FOU5hVE04cW5RZm1MenhXV013WTM4ejV3S29GYzF0LVQ3MWZoODhKTUUwU1JKTkFmb0E="
